#!/bin/sh

set -eu

error() {
  printf '%s\n' "ERROR: $*" >&2
}

info() {
  printf '%s\n' "INFO: $*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    error "Missing required command: $1"
    return 1
  fi
}

REPO_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

ENV_LOADER="${REPO_ROOT}/.devcontainer/scripts/env-loader.sh"
if [ -f "$ENV_LOADER" ]; then
  # shellcheck disable=SC1090
  . "$ENV_LOADER"
  load_project_env "$REPO_ROOT"
fi

if [ -z "${SITE_DOMAIN:-}" ]; then
  error "SITE_DOMAIN is not set. Set it in .env (see .env.example)."
  exit 1
fi

default_inventory="${REPO_ROOT}/src/inventory/hosts.ini"
inventory_arg="${1:-}"
inventory_env="${ANSIBLE_INVENTORY:-}"

if [ -n "$inventory_arg" ]; then
  inventory="$inventory_arg"
elif [ -n "$inventory_env" ] && [ -f "$inventory_env" ]; then
  inventory="$inventory_env"
elif [ -n "$inventory_env" ] && [ -f "$default_inventory" ]; then
  info "ANSIBLE_INVENTORY points to a missing file ($inventory_env); using repo inventory at $default_inventory"
  inventory="$default_inventory"
else
  inventory="$default_inventory"
fi
group="${HOSTS_SNIPPET_GROUP:-raspberry_pi_boxes}"

include_whoami="${HOSTS_SNIPPET_INCLUDE_WHOAMI:-true}"
include_traefik="${HOSTS_SNIPPET_INCLUDE_TRAEFIK_DASHBOARD:-auto}"
include_ca_share="${HOSTS_SNIPPET_INCLUDE_CA_SHARE:-auto}"

case "$include_whoami" in true|false) ;; *) error "HOSTS_SNIPPET_INCLUDE_WHOAMI must be true or false"; exit 1 ;; esac
case "$include_traefik" in auto|true|false) ;; *) error "HOSTS_SNIPPET_INCLUDE_TRAEFIK_DASHBOARD must be auto, true, or false"; exit 1 ;; esac
case "$include_ca_share" in auto|true|false) ;; *) error "HOSTS_SNIPPET_INCLUDE_CA_SHARE must be auto, true, or false"; exit 1 ;; esac

require_cmd ansible-inventory
require_cmd jq

if [ ! -f "$inventory" ]; then
  error "Inventory file not found: $inventory"
  exit 1
fi

case "$SITE_DOMAIN" in
  *.*) ;;
  *)
    error "SITE_DOMAIN must look like a DNS suffix (example: hhlab.home.arpa). Got: $SITE_DOMAIN"
    exit 1
    ;;
esac

if [ "${NAME_RESOLUTION_MODE:-hosts}" != "hosts" ]; then
  info "NAME_RESOLUTION_MODE is '${NAME_RESOLUTION_MODE:-}'. This generator is intended for NAME_RESOLUTION_MODE=hosts."
fi

if [ "$include_ca_share" = "auto" ]; then
  ca_share_enabled="${CA_SHARE_ENABLED:-false}"
  case "$(printf '%s' "$ca_share_enabled" | tr '[:upper:]' '[:lower:]')" in
    true) include_ca_share=true ;;
    *) include_ca_share=false ;;
  esac
fi

if [ "$include_traefik" = "auto" ]; then
  dashboard_enabled="${TRAEFIK_DASHBOARD_ENABLED:-false}"
  case "$(printf '%s' "$dashboard_enabled" | tr '[:upper:]' '[:lower:]')" in
    true) include_traefik=true ;;
    *) include_traefik=false ;;
  esac
fi

inventory_json=""
if ! inventory_json="$(ansible-inventory -i "$inventory" --list 2>/dev/null)"; then
  error "Failed to run ansible-inventory. Run this script inside the devcontainer (or ensure Ansible is installed on this machine)."
  exit 1
fi

if ! printf '%s' "$inventory_json" | jq -e --arg group "$group" '.[$group].hosts | type == "array"' >/dev/null 2>&1; then
  error "Inventory group '$group' not found, or it has no hosts. Set HOSTS_SNIPPET_GROUP to a valid group."
  exit 1
fi

tmp_tsv="${TMPDIR:-/tmp}/hosts-snippet.$$.tsv"
trap 'rm -f "$tmp_tsv" 2>/dev/null || true' EXIT HUP INT TERM

printf '%s' "$inventory_json" | jq -r \
  --arg group "$group" \
  --arg site_domain "$(printf '%s' "$SITE_DOMAIN" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')" '
    .[$group].hosts[]
    | . as $host
    | (._meta.hostvars[$host] // {}) as $hv
    | ($hv.ansible_host // $host) as $ip
    | ($hv.box_name // $host) as $box
    | ($hv.whoami_host // ("whoami." + $box + "." + $site_domain)) as $whoami
    | ($hv.ca_share_host // ("ca." + $box + "." + $site_domain)) as $ca
    | ($hv.traefik_dashboard_host // ("traefik." + $box + "." + $site_domain)) as $traefik
    | [$host, $ip, $box, $whoami, $ca, $traefik]
    | @tsv
  ' \
  | LC_ALL=C sort -t "$(printf '\t')" -k3,3 -k1,1 \
  >"$tmp_tsv"

printf '%s\n' "# -----------------------------------------------------------------------------"
printf '%s\n' "# /etc/hosts snippet (generated by $(basename "$0"))"
printf '%s\n' "# Group: ${group}"
printf '%s\n' "# SITE_DOMAIN: ${SITE_DOMAIN}"
printf '%s\n' "# Add these lines to your client /etc/hosts (NAME_RESOLUTION_MODE=hosts)."
printf '%s\n' "# -----------------------------------------------------------------------------"

while IFS="$(printf '\t')" read -r inv_host ip box whoami_host ca_share_host traefik_dashboard_host; do
  if [ -z "$ip" ]; then
    error "Host '$inv_host' has no ansible_host (and inventory hostname is empty)."
    exit 1
  fi

  box_lc="$(printf '%s' "$box" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')"
  if ! printf '%s' "$box_lc" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
    error "Host '$inv_host' box name '$box' is not a valid DNS label. Set host_var box_name (example: rpi-box-01)."
    exit 1
  fi

  names=""
  if [ "$include_whoami" = "true" ]; then
    names="${names} ${whoami_host}"
  fi
  if [ "$include_traefik" = "true" ]; then
    names="${names} ${traefik_dashboard_host}"
  fi
  if [ "$include_ca_share" = "true" ]; then
    names="${names} ${ca_share_host}"
  fi

  names="$(printf '%s' "$names" | tr -s ' ' | sed 's/^ *//; s/ *$//')"
  if [ -z "$names" ]; then
    continue
  fi

  printf '%s %s\n' "$ip" "$names"
done < "$tmp_tsv"
